import base64
import os
import requests
from flask import Flask, request, abort
from dotenv import load_dotenv

# Load environment variables from a .env file
load_dotenv()

# --- Configuration ---
# Make sure to set your GEMINI_API_KEY in a file named .env
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
if not GEMINI_API_KEY:
    raise ValueError("GEMINI_API_KEY not found. Please set it in your .env file.")

GEMINI_API_URL = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key={GEMINI_API_KEY}"

# --- Flask App ---
app = Flask(__name__)

@app.route('/ocr', methods=['POST'])
def handle_ocr_request():
    """
    This endpoint receives an image from ShareX, sends it to Gemini for OCR,
    and returns the extracted text.
    """
    # 1. Check if an image file is present in the request
    if 'image' not in request.files:
        abort(400, 'No image file found in the request.')

    image_file = request.files['image']

    # 2. Read image bytes and encode to base64
    image_bytes = image_file.read()
    mime_type = image_file.mimetype
    base64_image = base64.b64encode(image_bytes).decode('utf-8')

    # 3. Construct the request payload for Gemini API with the enhanced prompt
    gemini_payload = {
        "contents": [
            {
                "parts": [
                    # --- PROMPT ENHANCEMENT IS HERE ---
                    {"text": "Extract the text from this image. Preserve the original formatting, including line breaks, spacing, and layout, as accurately as possible. Return only the extracted text."},
                    {
                        "inline_data": {
                            "mime_type": mime_type,
                            "data": base64_image
                        }
                    }
                ]
            }
        ]
    }

    # 4. Send the request to the Gemini API
    try:
        response = requests.post(GEMINI_API_URL, json=gemini_payload)
        response.raise_for_status()  # Raise an exception for bad status codes (4xx or 5xx)
        
        # 5. Parse the response and extract the text
        response_data = response.json()
        
        # Navigate through the JSON structure to get the text
        # Added error handling for robustness
        candidates = response_data.get("candidates", [])
        if not candidates:
            return "No content generated by the API.", 500
        
        content = candidates[0].get("content", {})
        parts = content.get("parts", [])
        if not parts:
            return "No parts in the API response.", 500
            
        extracted_text = parts[0].get("text", "Could not extract text.")
        
        # 6. Return the extracted text to ShareX
        return extracted_text, 200, {'Content-Type': 'text/plain; charset=utf-8'}

    except requests.exceptions.RequestException as e:
        return f"Error communicating with Gemini API: {e}", 500
    except (KeyError, IndexError) as e:
        return f"Error parsing Gemini API response: {e}. Full response: {response.text}", 500


if __name__ == '__main__':
    # Runs the app on http://127.0.0.1:5000
    # You can change the port if needed.
    app.run(host='127.0.0.1', port=5000)